package models

const (
	AssessmentTeamStatusCreated = iota + 1
	AssessmentTeamStatusVerified
)

var AssessmentTeamStatuses = map[int]struct{}{
	AssessmentTeamStatusCreated:  {},
	AssessmentTeamStatusVerified: {},
}

const (
	AssessmentTeamAssessorRoleHead = iota + 1
	AssessmentTeamAssessorRoleVice
	AssessmentTeamAssessorRoleMember
)

var AssessmentTeamAssessorRoles = map[int]struct{}{
	AssessmentTeamAssessorRoleHead:   {},
	AssessmentTeamAssessorRoleVice:   {},
	AssessmentTeamAssessorRoleMember: {},
}

const (
	AssessmentTeamAssessorStatusAccepted = iota + 1
	AssessmentTeamAssessorStatusRejected
)

var AssessmentTeamAssessorStatuses = map[int]struct{}{
	AssessmentTeamAssessorStatusAccepted: {},
	AssessmentTeamAssessorStatusRejected: {},
}

// AssessmentTeamAdmission represents a single assessment admission request.
type AssessmentTeamAdmission struct {
	AdmissionNumber      string      `json:"no_usulan"`
	FunctionalPositionId string      `json:"jabatan_fungsional_id"`
	AdmissionDate        Iso8601Date `json:"tgl_usulan"`

	// TempSupportDocuments contains a list of UUIDs previously generated by us.
	// Each UUID in this array corresponds to a single temporary file previously uploaded by the frontend. The
	// UUID is a key that we give for each document. This way we understand which documents we need to drag from
	// the temporary locations to persistent storage/database.
	TempSupportDocuments []*Document `json:"temp_dokumen_pendukung,omitempty"`

	// Assessors is the list of assessors for the assessment team.
	Assessors []*Assessor `json:"penilai,omitempty"`

	// SubmitterAsnId is the ASN ID of the submitter (the user), can be retrieved from ID token.
	SubmitterAsnId string `json:"-"`
	AgencyId       string `json:"-"`
}

// AssessmentTeam represents a single assessment team.
type AssessmentTeam struct {
	AssessmentTeamId     string      `json:"tim_penilaian_id"`
	AdmissionNumber      string      `json:"no_usulan"`
	FunctionalPositionId string      `json:"jabatan_fungsional_id"`
	FunctionalPosition   string      `json:"jabatan_fungsional"`
	Status               int         `json:"status"`
	Agency               string      `json:"instansi"`
	AgencyId             string      `json:"instansi_id"`
	AdmissionDate        Iso8601Date `json:"tgl_usulan"`

	// Assessors is the list of assessors for the assessment team.
	Assessors []*Assessor `json:"penilai,omitempty"`

	// SupportDocuments is the list of supporting documents metadata for a particular assessment team admission.
	SupportDocuments []*Document `json:"dokumen_pendukung,omitempty"`

	// RecommendationLetter is the recommendation letter metadata for a particular assessment team verification.
	RecommendationLetter *Document `json:"surat_rekomendasi,omitempty"`
}

// Assessor represents a single entry of assessment team assessor.
type Assessor struct {
	AsnId          string `json:"asn_id"`
	Nip            string `json:"nip"`
	Name           string `json:"nama"`
	Role           int    `json:"peran"`
	Status         int    `json:"status"`
	ReasonRejected string `json:"alasan_ditolak"`
}

// AssessmentTeamItem represents a single assessment team item when search for admission.
type AssessmentTeamItem struct {
	AssessmentTeamId string      `json:"tim_penilaian_id"`
	AdmissionNumber  string      `json:"no_usulan"`
	Status           int         `json:"status"`
	Agency           string      `json:"instansi"`
	AgencyId         string      `json:"instansi_id"`
	AdmissionDate    Iso8601Date `json:"tgl_usulan"`
}

// AssessmentTeamVerification represents a single assessment team verification request.
type AssessmentTeamVerification struct {
	AssessmentTeamId string `json:"tim_penilaian_id"`

	// Assessors is the list of assessors for the assessment team.
	Assessors []*Assessor `json:"penilai,omitempty"`

	TempRecommendationLetter *Document `json:"temp_surat_rekomendasi,omitempty"`

	// SubmitterAsnId is the ASN ID of the submitter (the user), can be retrieved from ID token.
	SubmitterAsnId string `json:"-"`
}
