package models

const (
	DismissalAdmissionStatusCreated = iota + 1
	DismissalAdmissionStatusAccepted
	DismissalAdmissionStatusRejected
)

var DismissalAdmissionStatuses = map[int]struct{}{
	DismissalAdmissionStatusCreated:  {},
	DismissalAdmissionStatusAccepted: {},
	DismissalAdmissionStatusRejected: {},
}

type DismissalAdmission struct {
	DismissalId string    `json:"pemberhentian_id"`
	AsnId       string    `json:"asn_id"`
	AsnName     string    `json:"nama"`
	AsnNip      string    `json:"nip"`
	Status      int       `json:"status"`
	StatusTs    EpochTime `json:"status_ts"`
	StatusBy    string    `json:"status_by"`

	DismissalReason            string    `json:"alasan_pemberhentian,omitempty"`
	DismissalLetter            *Document `json:"surat_pemberhentian,omitempty"`
	DismissalLetterSignerAsnId string    `json:"pejabat_penandatangan_surat_pemberhentian,omitempty"`

	DismissalDenyReason           string      `json:"alasan_tidak_diberhentikan,omitempty"`
	DismissalDenySupportDocuments []*Document `json:"dokumen_pendukung_tidak_diberhentikan,omitempty"`

	// TempSupportDocuments contains a list of UUIDs previously generated by us.
	// Each UUID in this array corresponds to a single temporary file previously uploaded by the frontend. The
	// UUID is a key that we give for each document. This way we understand which documents we need to drag from
	// the temporary locations to persistent storage/database.
	TempSupportDocuments []*Document `json:"temp_dokumen_pendukung,omitempty"`

	// SupportDocuments is the list of supporting documents metadata for a particular activity admission.
	SupportDocuments []*Document `json:"dokumen_pendukung,omitempty"`

	DismissalDate Iso8601Date `json:"tgl_pemberhentian"`

	DecreeNumber string      `json:"nomor_sk"`
	DecreeDate   Iso8601Date `json:"tgl_sk"`
	ReasonDetail string      `json:"detail_alasan"`

	// A generic freetext again.
	AdmissionNumber string `json:"no_usulan"`

	// SubmitterAsnId is the ASN ID of the submitter (the user), can be retrieved from ID token.
	SubmitterAsnId string `json:"-"`
	AgencyId       string `json:"-"`
}

type DismissalAcceptanceRequest struct {
	DismissalId     string    `json:"pemberhentian_id"`
	DismissalLetter *Document `json:"surat_pemberhentian"`

	// DismissalLetterSignerAsnId is the ASN ID of the person who signed the recommendation letter.
	DismissalLetterSignerAsnId string `json:"pejabat_penandatangan_surat_pemberhentian"`

	// SubmitterAsnId is the ASN ID of the submitter (the user), can be retrieved from ID token.
	SubmitterAsnId string `json:"-"`
	AgencyId       string `json:"-"`
}

type DismissalDenyRequest struct {
	DismissalId                       string      `json:"pemberhentian_id"`
	DismissalDenyReason               string      `json:"alasan_tidak_diberhentikan"`
	TempDismissalDenySupportDocuments []*Document `json:"temp_dokumen_pendukung_tidak_diberhentikan"`

	// SubmitterAsnId is the ASN ID of the submitter (the user), can be retrieved from ID token.
	SubmitterAsnId string `json:"-"`
	AgencyId       string `json:"-"`
}
